export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"

export const UPDATE_PROFILE = "UPDATE_PROFILE"